{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vsf-miniapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vsf-miniapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vsf-miniapp.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.monitoring.serviceMonitor.port }}
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
