apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: linkerd-viz

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: linkerd-viz
        labels:
          environment: staging
    target:
      kind: Namespace
      name: linkerd-viz
