{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "my-microservice.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-microservice.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "my-microservice.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "my-microservice.labels" . | nindent 10 }}
        annotations:
          reloader.stakater.com/match: "true"
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
