apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - middleware-default-headers.yaml
  - middleware-rate-limit.yaml
  - ingressroute-dashboard.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: traefik
