apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Development environment overlay for Secrets Store CSI
resources:
  - ../../base

namespace: kube-system

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-system
        labels:
          environment: dev
    target:
      kind: Namespace
      name: kube-system
