apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Development environment overlay for Traefik
resources:
  - ../../base

namespace: traefik

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: traefik
        labels:
          environment: dev
    target:
      kind: Namespace
      name: traefik
