apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Development environment overlay for Linkerd
resources:
  - ../../base

namespace: linkerd

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: linkerd
        labels:
          environment: dev
    target:
      kind: Namespace
      name: linkerd
