apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd-viz

resources:
  - namespace.yaml
  - ingress.yaml  # Contains Middleware, Secret, and Certificate
  - httproute.yaml  # Gateway API HTTPRoute
  - rbac-cross-namespace.yaml
