apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - ./
      lockRepo: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
data:
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
---
# Example: Using AVP in your application manifests
# You can reference Vault secrets like this:
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-app-secret
#   annotations:
#     avp.kubernetes.io/path: "secret/data/myapp"
# type: Opaque
# stringData:
#   password: <password>
#   api-key: <api_key>
#
# Or using path syntax:
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-app-secret
# type: Opaque
# stringData:
#   password: <path:secret/data/myapp#password>
#   api-key: <path:secret/data/myapp#api_key>
