apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
  - linkerd-issuer.yaml
  - namespace.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: linkerd-identity-trust-roots
        annotations:
          cert-manager.io/inject-ca-from: linkerd/linkerd-trust-anchor
    target:
      kind: ConfigMap
      name: linkerd-identity-trust-roots