# Linkerd Development Values (Single Node)
identity:
  issuer:
    scheme: kubernetes.io/tls
  externalCA: true
  externalIssuer:
    certificate: linkerd-identity-issuer # Cert-manager created secret for intermediate issuer
    # The Linkerd Helm chart will look for a Secret named linkerd-identity-issuer
    # in the linkerd namespace. This Secret should be type kubernetes.io/tls
    # and contain 'tls.crt' and 'tls.key'.

controllerReplicas: 1
enablePodAntiAffinity: false

controllerResources:
  cpu:
    request: 100m
  memory:
    request: 128Mi
  limit:
    cpu: 1000m
    memory: 1Gi

destinationResources:
  cpu:
    request: 100m
  memory:
    request: 128Mi
  limit:
    cpu: 1000m
    memory: 512Mi

proxy:
  enableExternalProfiles: true
  resources:
    cpu:
      request: 100m
    memory:
      request: 128Mi
    limit:
      cpu: 500m
      memory: 256Mi

proxyInjector:
  externalSecret: false
  resources:
    cpu:
      request: 100m
    memory:
      request: 128Mi
    limit:
      cpu: 500m
      memory: 256Mi

profileValidator:
  externalSecret: false
  resources:
    cpu:
      request: 100m
    memory:
      request: 128Mi
    limit:
      cpu: 500m
      memory: 256Mi

policyValidator:
  externalSecret: false
  resources:
    cpu:
      request: 100m
    memory:
      request: 128Mi
    limit:
      cpu: 500m
      memory: 256Mi

disableHeartBeat: false